// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: behaviour_traits.sql

package dbgen

import (
	"context"

	"github.com/vd09-projects/swipeassist/domain"
)

const getBehaviourTraits = `-- name: GetBehaviourTraits :one
SELECT
    id,
    profile_key,
    app,
    traits,
    created_at
FROM behaviour_traits
WHERE id = $1
`

func (q *Queries) GetBehaviourTraits(ctx context.Context, id int64) (BehaviourTrait, error) {
	row := q.db.QueryRow(ctx, getBehaviourTraits, id)
	var i BehaviourTrait
	err := row.Scan(
		&i.ID,
		&i.ProfileKey,
		&i.App,
		&i.Traits,
		&i.CreatedAt,
	)
	return i, err
}

const insertBehaviourTraits = `-- name: InsertBehaviourTraits :one

INSERT INTO behaviour_traits (
    profile_key,
    app,
    traits
) VALUES ($1, $2, $3)
RETURNING id, profile_key, app, traits, created_at
`

type InsertBehaviourTraitsParams struct {
	ProfileKey *string                `json:"profile_key"`
	App        domain.AppName         `json:"app"`
	Traits     domain.BehaviourTraits `json:"traits"`
}

// Store and fetch BehaviourTraits snapshots.
func (q *Queries) InsertBehaviourTraits(ctx context.Context, arg InsertBehaviourTraitsParams) (BehaviourTrait, error) {
	row := q.db.QueryRow(ctx, insertBehaviourTraits, arg.ProfileKey, arg.App, arg.Traits)
	var i BehaviourTrait
	err := row.Scan(
		&i.ID,
		&i.ProfileKey,
		&i.App,
		&i.Traits,
		&i.CreatedAt,
	)
	return i, err
}

const listBehaviourTraitsByProfile = `-- name: ListBehaviourTraitsByProfile :many
SELECT
    id,
    profile_key,
    app,
    traits,
    created_at
FROM behaviour_traits
WHERE profile_key = $1
ORDER BY created_at DESC
`

func (q *Queries) ListBehaviourTraitsByProfile(ctx context.Context, profileKey *string) ([]BehaviourTrait, error) {
	rows, err := q.db.Query(ctx, listBehaviourTraitsByProfile, profileKey)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BehaviourTrait
	for rows.Next() {
		var i BehaviourTrait
		if err := rows.Scan(
			&i.ID,
			&i.ProfileKey,
			&i.App,
			&i.Traits,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentBehaviourTraits = `-- name: ListRecentBehaviourTraits :many
SELECT
    id,
    profile_key,
    app,
    traits,
    created_at
FROM behaviour_traits
ORDER BY created_at DESC
LIMIT $1
`

func (q *Queries) ListRecentBehaviourTraits(ctx context.Context, limit int32) ([]BehaviourTrait, error) {
	rows, err := q.db.Query(ctx, listRecentBehaviourTraits, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BehaviourTrait
	for rows.Next() {
		var i BehaviourTrait
		if err := rows.Scan(
			&i.ID,
			&i.ProfileKey,
			&i.App,
			&i.Traits,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
