// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: llm_requests.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
	"github.com/vd09-projects/swipeassist/domain"
)

const getLLMRequest = `-- name: GetLLMRequest :one
SELECT
    id,
    kind,
    profile_key,
    app,
    template_path,
    prompt_text,
    vars,
    model,
    status,
    error_message,
    parent_request_id,
    created_at,
    completed_at
FROM llm_requests
WHERE id = $1
`

func (q *Queries) GetLLMRequest(ctx context.Context, id int64) (LlmRequest, error) {
	row := q.db.QueryRow(ctx, getLLMRequest, id)
	var i LlmRequest
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.ProfileKey,
		&i.App,
		&i.TemplatePath,
		&i.PromptText,
		&i.Vars,
		&i.Model,
		&i.Status,
		&i.ErrorMessage,
		&i.ParentRequestID,
		&i.CreatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const insertBehaviourResponse = `-- name: InsertBehaviourResponse :one
INSERT INTO behaviour_responses (
    request_id,
    traits_json,
    raw_response
) VALUES ($1, $2, $3)
RETURNING
    id,
    request_id,
    traits_json,
    raw_response,
    created_at
`

type InsertBehaviourResponseParams struct {
	RequestID   int64                  `json:"request_id"`
	TraitsJson  domain.BehaviourTraits `json:"traits_json"`
	RawResponse []byte                 `json:"raw_response"`
}

func (q *Queries) InsertBehaviourResponse(ctx context.Context, arg InsertBehaviourResponseParams) (BehaviourResponse, error) {
	row := q.db.QueryRow(ctx, insertBehaviourResponse, arg.RequestID, arg.TraitsJson, arg.RawResponse)
	var i BehaviourResponse
	err := row.Scan(
		&i.ID,
		&i.RequestID,
		&i.TraitsJson,
		&i.RawResponse,
		&i.CreatedAt,
	)
	return i, err
}

const insertLLMRequest = `-- name: InsertLLMRequest :one

INSERT INTO llm_requests (
    kind,
    profile_key,
    app,
    template_path,
    prompt_text,
    vars,
    model,
    status,
    error_message,
    parent_request_id
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING
    id,
    kind,
    profile_key,
    app,
    template_path,
    prompt_text,
    vars,
    model,
    status,
    error_message,
    parent_request_id,
    created_at,
    completed_at
`

type InsertLLMRequestParams struct {
	Kind            ExtractionKind `json:"kind"`
	ProfileKey      *string        `json:"profile_key"`
	App             domain.AppName `json:"app"`
	TemplatePath    string         `json:"template_path"`
	PromptText      string         `json:"prompt_text"`
	Vars            []byte         `json:"vars"`
	Model           string         `json:"model"`
	Status          string         `json:"status"`
	ErrorMessage    *string        `json:"error_message"`
	ParentRequestID *int64         `json:"parent_request_id"`
}

// Store and fetch LLM extraction requests and their outputs.
func (q *Queries) InsertLLMRequest(ctx context.Context, arg InsertLLMRequestParams) (LlmRequest, error) {
	row := q.db.QueryRow(ctx, insertLLMRequest,
		arg.Kind,
		arg.ProfileKey,
		arg.App,
		arg.TemplatePath,
		arg.PromptText,
		arg.Vars,
		arg.Model,
		arg.Status,
		arg.ErrorMessage,
		arg.ParentRequestID,
	)
	var i LlmRequest
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.ProfileKey,
		&i.App,
		&i.TemplatePath,
		&i.PromptText,
		&i.Vars,
		&i.Model,
		&i.Status,
		&i.ErrorMessage,
		&i.ParentRequestID,
		&i.CreatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const insertLLMRequestMedia = `-- name: InsertLLMRequestMedia :one
INSERT INTO llm_request_media (
    request_id,
    position,
    uri,
    media_type
) VALUES ($1, $2, $3, $4)
RETURNING
    id,
    request_id,
    position,
    uri,
    media_type,
    created_at
`

type InsertLLMRequestMediaParams struct {
	RequestID int64  `json:"request_id"`
	Position  int32  `json:"position"`
	Uri       string `json:"uri"`
	MediaType string `json:"media_type"`
}

func (q *Queries) InsertLLMRequestMedia(ctx context.Context, arg InsertLLMRequestMediaParams) (LlmRequestMedium, error) {
	row := q.db.QueryRow(ctx, insertLLMRequestMedia,
		arg.RequestID,
		arg.Position,
		arg.Uri,
		arg.MediaType,
	)
	var i LlmRequestMedium
	err := row.Scan(
		&i.ID,
		&i.RequestID,
		&i.Position,
		&i.Uri,
		&i.MediaType,
		&i.CreatedAt,
	)
	return i, err
}

const insertPhotoPersonaResponse = `-- name: InsertPhotoPersonaResponse :one
INSERT INTO photo_persona_responses (
    request_id,
    persona_json,
    raw_response
) VALUES ($1, $2, $3)
RETURNING
    id,
    request_id,
    persona_json,
    raw_response,
    created_at
`

type InsertPhotoPersonaResponseParams struct {
	RequestID   int64                     `json:"request_id"`
	PersonaJson domain.PhotoPersonaBundle `json:"persona_json"`
	RawResponse []byte                    `json:"raw_response"`
}

func (q *Queries) InsertPhotoPersonaResponse(ctx context.Context, arg InsertPhotoPersonaResponseParams) (PhotoPersonaResponse, error) {
	row := q.db.QueryRow(ctx, insertPhotoPersonaResponse, arg.RequestID, arg.PersonaJson, arg.RawResponse)
	var i PhotoPersonaResponse
	err := row.Scan(
		&i.ID,
		&i.RequestID,
		&i.PersonaJson,
		&i.RawResponse,
		&i.CreatedAt,
	)
	return i, err
}

const listLLMRequestMedia = `-- name: ListLLMRequestMedia :many
SELECT
    id,
    request_id,
    position,
    uri,
    media_type,
    created_at
FROM llm_request_media
WHERE request_id = $1
ORDER BY position
`

func (q *Queries) ListLLMRequestMedia(ctx context.Context, requestID int64) ([]LlmRequestMedium, error) {
	rows, err := q.db.Query(ctx, listLLMRequestMedia, requestID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LlmRequestMedium
	for rows.Next() {
		var i LlmRequestMedium
		if err := rows.Scan(
			&i.ID,
			&i.RequestID,
			&i.Position,
			&i.Uri,
			&i.MediaType,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateLLMRequestStatus = `-- name: UpdateLLMRequestStatus :exec
UPDATE llm_requests
SET
    status = $2,
    error_message = $3,
    completed_at = $4
WHERE id = $1
`

type UpdateLLMRequestStatusParams struct {
	ID           int64              `json:"id"`
	Status       string             `json:"status"`
	ErrorMessage *string            `json:"error_message"`
	CompletedAt  pgtype.Timestamptz `json:"completed_at"`
}

func (q *Queries) UpdateLLMRequestStatus(ctx context.Context, arg UpdateLLMRequestStatusParams) error {
	_, err := q.db.Exec(ctx, updateLLMRequestStatus,
		arg.ID,
		arg.Status,
		arg.ErrorMessage,
		arg.CompletedAt,
	)
	return err
}
