// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package dbgen

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
	"github.com/vd09-projects/swipeassist/domain"
)

type AppActionKind string

const (
	AppActionKindPASS       AppActionKind = "PASS"
	AppActionKindLIKE       AppActionKind = "LIKE"
	AppActionKindSUPERSWIPE AppActionKind = "SUPERSWIPE"
)

func (e *AppActionKind) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AppActionKind(s)
	case string:
		*e = AppActionKind(s)
	default:
		return fmt.Errorf("unsupported scan type for AppActionKind: %T", src)
	}
	return nil
}

type NullAppActionKind struct {
	AppActionKind AppActionKind `json:"app_action_kind"`
	Valid         bool          `json:"valid"` // Valid is true if AppActionKind is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAppActionKind) Scan(value interface{}) error {
	if value == nil {
		ns.AppActionKind, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AppActionKind.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAppActionKind) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AppActionKind), nil
}

type BehaviourTrait struct {
	ID         int64                  `json:"id"`
	ProfileKey *string                `json:"profile_key"`
	App        domain.AppName         `json:"app"`
	Traits     domain.BehaviourTraits `json:"traits"`
	CreatedAt  pgtype.Timestamptz     `json:"created_at"`
}

type Decision struct {
	ID            int64                `json:"id"`
	ProfileKey    *string              `json:"profile_key"`
	App           domain.AppName       `json:"app"`
	PolicyName    string               `json:"policy_name"`
	ActionKind    domain.AppActionType `json:"action_kind"`
	ActionMessage *string              `json:"action_message"`
	Score         int                  `json:"score"`
	Reason        string               `json:"reason"`
	CreatedAt     pgtype.Timestamptz   `json:"created_at"`
}
