// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package dbgen

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
	"github.com/vd09-projects/swipeassist/domain"
)

type AppActionKind string

const (
	AppActionKindPASS       AppActionKind = "PASS"
	AppActionKindLIKE       AppActionKind = "LIKE"
	AppActionKindSUPERSWIPE AppActionKind = "SUPERSWIPE"
)

func (e *AppActionKind) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AppActionKind(s)
	case string:
		*e = AppActionKind(s)
	default:
		return fmt.Errorf("unsupported scan type for AppActionKind: %T", src)
	}
	return nil
}

type NullAppActionKind struct {
	AppActionKind AppActionKind `json:"app_action_kind"`
	Valid         bool          `json:"valid"` // Valid is true if AppActionKind is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAppActionKind) Scan(value interface{}) error {
	if value == nil {
		ns.AppActionKind, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AppActionKind.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAppActionKind) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AppActionKind), nil
}

type ExtractionKind string

const (
	ExtractionKindBehaviour    ExtractionKind = "behaviour"
	ExtractionKindPhotoPersona ExtractionKind = "photo_persona"
)

func (e *ExtractionKind) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ExtractionKind(s)
	case string:
		*e = ExtractionKind(s)
	default:
		return fmt.Errorf("unsupported scan type for ExtractionKind: %T", src)
	}
	return nil
}

type NullExtractionKind struct {
	ExtractionKind ExtractionKind `json:"extraction_kind"`
	Valid          bool           `json:"valid"` // Valid is true if ExtractionKind is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullExtractionKind) Scan(value interface{}) error {
	if value == nil {
		ns.ExtractionKind, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ExtractionKind.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullExtractionKind) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ExtractionKind), nil
}

type BehaviourResponse struct {
	ID          int64                  `json:"id"`
	RequestID   int64                  `json:"request_id"`
	TraitsJson  domain.BehaviourTraits `json:"traits_json"`
	RawResponse []byte                 `json:"raw_response"`
	CreatedAt   pgtype.Timestamptz     `json:"created_at"`
}

type BehaviourTrait struct {
	ID         int64                  `json:"id"`
	ProfileKey *string                `json:"profile_key"`
	App        domain.AppName         `json:"app"`
	Traits     domain.BehaviourTraits `json:"traits"`
	CreatedAt  pgtype.Timestamptz     `json:"created_at"`
}

type Decision struct {
	ID            int64                `json:"id"`
	ProfileKey    *string              `json:"profile_key"`
	App           domain.AppName       `json:"app"`
	PolicyName    string               `json:"policy_name"`
	ActionKind    domain.AppActionType `json:"action_kind"`
	ActionMessage *string              `json:"action_message"`
	Score         int                  `json:"score"`
	Reason        string               `json:"reason"`
	CreatedAt     pgtype.Timestamptz   `json:"created_at"`
}

type LlmRequest struct {
	ID              int64              `json:"id"`
	Kind            ExtractionKind     `json:"kind"`
	ProfileKey      *string            `json:"profile_key"`
	App             domain.AppName     `json:"app"`
	TemplatePath    string             `json:"template_path"`
	PromptText      string             `json:"prompt_text"`
	Vars            []byte             `json:"vars"`
	Model           string             `json:"model"`
	Status          string             `json:"status"`
	ErrorMessage    *string            `json:"error_message"`
	ParentRequestID *int64             `json:"parent_request_id"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	CompletedAt     pgtype.Timestamptz `json:"completed_at"`
}

type LlmRequestMedium struct {
	ID        int64              `json:"id"`
	RequestID int64              `json:"request_id"`
	Position  int32              `json:"position"`
	Uri       string             `json:"uri"`
	MediaType string             `json:"media_type"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type PhotoPersonaResponse struct {
	ID          int64                     `json:"id"`
	RequestID   int64                     `json:"request_id"`
	PersonaJson domain.PhotoPersonaBundle `json:"persona_json"`
	RawResponse []byte                    `json:"raw_response"`
	CreatedAt   pgtype.Timestamptz        `json:"created_at"`
}
