-- Store and fetch decisions generated by the decision engine.

-- name: InsertDecision :one
INSERT INTO decisions (
    profile_key,
    app,
    policy_name,
    action_kind,
    action_message,
    score,
    reason
) VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, profile_key, app, policy_name, action_kind, action_message, score, reason, created_at;

-- name: GetDecision :one
SELECT
    id,
    profile_key,
    app,
    policy_name,
    action_kind,
    action_message,
    score,
    reason,
    created_at
FROM decisions
WHERE id = $1;

-- name: ListDecisionsByProfile :many
SELECT
    id,
    profile_key,
    app,
    policy_name,
    action_kind,
    action_message,
    score,
    reason,
    created_at
FROM decisions
WHERE profile_key = $1
ORDER BY created_at DESC;

-- name: ListRecentDecisions :many
SELECT
    id,
    profile_key,
    app,
    policy_name,
    action_kind,
    action_message,
    score,
    reason,
    created_at
FROM decisions
ORDER BY created_at DESC
LIMIT $1;
